apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-a-selvin
  namespace: pruebas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-a-selvin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-a-selvin
    spec:
      containers:
        - image: selvinmedina/api-a
          imagePullPolicy: Always
          name: api-a-selvin
          env:
            - name: SALUDO
              value: Hola desde Kubernetes edits 4 veces
      restartPolicy: Always