apiVersion: v1
kind: Service
metadata:
  name: api-a-selvin-svc
  namespace: pruebas
spec:
  selector:
    app: api-a-selvin
  type: NodePort
  ports:
    - port: 80
      nodePort: 30036
      name: http